version: '3.9'
services:
  messaging:
    container_name: messaging
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 80
    volumes:
      - ./app:/app
    networks:
      - sample-app-core_default
    environment:
      - WATCHFILES_FORCE_POLLING=true

networks:
  sample-app-core_default:
    external: true