version: '3.9'
services:
  email_sender:
    container_name: email_sender
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python -u main.py
    volumes:
      - ./app:/app
    networks:
      - sample-app-core_default

networks:
  sample-app-core_default:
    external: true