---
name: Messaging Build and Test
on: 
  pull_request:
    branches: [ dev, main ]

env:
  CONTAINER_REGISTRY_URI: acrsampleappneu.azurecr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install autopep8
        run: pip install flake8

      - name: Run linter
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          flake8_args: "--max-line-length=120"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Messaging Docker image
        run: docker build -t $CONTAINER_REGISTRY_URI/messaging:test -f ./Dockerfile .